export const messageTypes = {
  createChannel: BigInt(100),
  referenceChannel: BigInt(101),
  editChannelUri: BigInt(102),
  editChannelAccess: BigInt(103),
  createPublication: BigInt(200),
  referencePublication: BigInt(201),
  editPublicationUri: BigInt(202),
  createNft: BigInt(300),
  referenceNft: BigInt(301),
  createUrl: BigInt(400),
  referenceUrl: BigInt(401),
  editUrl: BigInt(402),
  removeReference: BigInt(500),
}
