interface Env {
  NEXT_PUBLIC_ALCHEMY_KEY: string;
  NEXT_PUBLIC_WALLET_CONNECT_ID: string;
  NEXT_PUBLIC_GRAPHQL_API: string;
  NEXT_PUBLIC_WEB3STORAGE_TOKEN: string;
  NEXT_PUBLIC_BASEMENT_API: string;
}

const env: Env = {
  NEXT_PUBLIC_ALCHEMY_KEY: process.env.NEXT_PUBLIC_ALCHEMY_KEY as string,
  NEXT_PUBLIC_WALLET_CONNECT_ID: process.env
    .NEXT_PUBLIC_WALLET_CONNECT_ID as string,
  NEXT_PUBLIC_GRAPHQL_API: process.env.NEXT_PUBLIC_GRAPHQL_API as string,
  NEXT_PUBLIC_WEB3STORAGE_TOKEN: process.env
    .NEXT_PUBLIC_WEB3STORAGE_TOKEN as string,
  NEXT_PUBLIC_BASEMENT_API: process.env.NEXT_PUBLIC_BASEMENT_API as string,
};
